# Generated by Django 5.2.5 on 2025-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_persons',
            field=models.CharField(blank=True, max_length=300, verbose_name='关联人（可用逗号分隔）'),
        ),
    ]
